---
title: "pH"

---
###What is pH?

The basic equation for pH is below. It is a measure of the concentration of hydrogen ions in solution (often referred to as 'protons' since they carry one proton). What does this mean? Well, hydrogen atoms are one of the more readily transferred atoms between any chemical constituent of the soil. Their mobility often determines solubility and reactivity in water as the loss of a hydrogen atoms can lead to ionization of a compound. Thus the basic equation for understanding pH is below.
$$pH=-log_{10}[H^{+}]$$

A more nuanced equation helps understand what controls pH in a system:  the henderson hasselbach equation (below), which helps understand the influence of pH on a system through the pKa property. The pKa of a molecule is the pH of a solution where the acid (HA) and base (A^-^) forms of that molecule are present in equal concentrations. What does this mean? At pH greater than the pKa the base anionic form will dominate, potentially leading to 'deprotonation', or removal of a hydrogen, and resultant ionization of that molecule. At pH below the pKa the acid, or 'protonated' form predominates resulting in precipitation, or the insoluble phase as the dominant form. There is more complicated chemistry that occurrs at mineral surfaces that I can't get into here. But overall, just know that pH both relates to and controls solublity of ions in solution.

$$pH=pK_{a} + log_{10}[A^{-}/HA]$$

###How to measure pH

There is no one way to measure soil pH, so more important than anything is to measure pH the same way every time, but here's an accepted method that uses 2:1 water:soil. If you want to learn all there is to know about pH and soil see the [handbook of soil analysis](http://www.geokniga.org/bookfiles/geokniga-handbook-soil-analysis.pdf)

####Materials
pH probe
Buffers for calibration (commonly pH 2, 4, 7, and possibly 9)

####Procedure

#####Plain Water
1. Mix 10 grams soil with 20 mL water in a 120 mL specimen cup.
2. Stir with a glass rod several times over the course of 10 minutes.
3. Stir at 10 mintues, then let sit for 5 minutes.
4. Calibrate pH electrode with reference buffers.
5. Wash pH electrode with DI water, dab dry with kimwipe, and submerge in the suspension (do not let electrode touch the bottom, or the soil solution)

##### Exchangeable Acidity - CaCl~2~
Repeat the procedure, but instead of plain water, use 0.01 M CaCl~2~.

This is done because Ca^2+^ is a strong sorbent, and commonly Al3+ is the most concentrated cation on the mineral exchange complex. As a result, CaCl~2~ solution can be used in place of water to assess the exchangeable acidity. Al^3+^ is released, it hydrolyzes water, and generates greater acidity. This is relates to why soils become more acidic as they weather. 